# NumPy Array in Python
## Introduction to NumPy Arrays
NumPy (Numerical Python) is a library for Python programming that supports large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.

Creating NumPy Arrays
Importing NumPy
To use NumPy, you first need to import it:

In [1]:
import numpy as np


## Creating Arrays
From a List
You can create a NumPy array from a Python list or tuple using the np.array function:



In [1]:
import numpy as np

s = [12,76,87,86]

s*2

[12, 76, 87, 86, 12, 76, 87, 86]

In [3]:
d = np.array(s)

d*2

array([ 24, 152, 174, 172])

In [6]:
d

array([12, 76, 87, 86])

In [7]:
d+10

array([22, 86, 97, 96])

# From a Tuple
Similarly, you can create an array from a tuple:

In [8]:
f = (123,345,45,46,68)

f

(123, 345, 45, 46, 68)

In [9]:
g = np.array(f)
g

array([123, 345,  45,  46,  68])

In [10]:
type(g)

numpy.ndarray

# Using Built-in Functions
NumPy provides several functions to create arrays with specific values:

np.zeros(shape): Creates an array filled with zeros.

In [14]:
# np.zeros((shape))

np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

# np.ones(shape): Creates an array filled with ones.

In [17]:
np.ones((5,5))*100

array([[100., 100., 100., 100., 100.],
       [100., 100., 100., 100., 100.],
       [100., 100., 100., 100., 100.],
       [100., 100., 100., 100., 100.],
       [100., 100., 100., 100., 100.]])

# np.full(shape, fill_value): Creates an array filled with a specified value.

In [21]:
np.full((5,3),'007')

array([['007', '007', '007'],
       ['007', '007', '007'],
       ['007', '007', '007'],
       ['007', '007', '007'],
       ['007', '007', '007']], dtype='<U3')

In [25]:
np.random.randint(1,100,(3,3,3))

array([[[47, 34, 17],
        [13, 35, 27],
        [28, 99, 23]],

       [[53, 20,  6],
        [67,  4, 86],
        [56, 43, 11]],

       [[74, 87, 92],
        [67, 85, 19],
        [80, 75, 37]]])

# np.eye(n): Creates an identity matrix.

In [27]:
np.eye((5))

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# np.arange(start, stop, step): Creates an array with a range of values.

In [29]:
np.arange(0,25,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

In [31]:
len(np.arange(0,25))

25

In [35]:
np.arange(0,25).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

# np.linspace(start, stop, num): Creates an array with linearly spaced values.

In [38]:
np.linspace(1,50,500)

array([ 1.        ,  1.09819639,  1.19639279,  1.29458918,  1.39278557,
        1.49098196,  1.58917836,  1.68737475,  1.78557114,  1.88376754,
        1.98196393,  2.08016032,  2.17835671,  2.27655311,  2.3747495 ,
        2.47294589,  2.57114228,  2.66933868,  2.76753507,  2.86573146,
        2.96392786,  3.06212425,  3.16032064,  3.25851703,  3.35671343,
        3.45490982,  3.55310621,  3.65130261,  3.749499  ,  3.84769539,
        3.94589178,  4.04408818,  4.14228457,  4.24048096,  4.33867735,
        4.43687375,  4.53507014,  4.63326653,  4.73146293,  4.82965932,
        4.92785571,  5.0260521 ,  5.1242485 ,  5.22244489,  5.32064128,
        5.41883768,  5.51703407,  5.61523046,  5.71342685,  5.81162325,
        5.90981964,  6.00801603,  6.10621242,  6.20440882,  6.30260521,
        6.4008016 ,  6.498998  ,  6.59719439,  6.69539078,  6.79358717,
        6.89178357,  6.98997996,  7.08817635,  7.18637275,  7.28456914,
        7.38276553,  7.48096192,  7.57915832,  7.67735471,  7.77

In [40]:
b = np.random.randint(1,100,(3,3,3))
b

array([[[16, 65, 91],
        [95, 76, 74],
        [50, 46, 23]],

       [[ 8, 86, 60],
        [99, 32, 68],
        [30, 92, 39]],

       [[33, 61, 52],
        [36,  6, 30],
        [22,  4, 93]]])

In [41]:
b.flatten()

array([16, 65, 91, 95, 76, 74, 50, 46, 23,  8, 86, 60, 99, 32, 68, 30, 92,
       39, 33, 61, 52, 36,  6, 30, 22,  4, 93])

# Array Attributes
NumPy arrays have several attributes that provide useful information about the array.

In [42]:
b = np.random.randint(1,55,(5,5))
b

array([[21, 10, 14, 17, 19],
       [ 6, 12, 39, 47, 12],
       [17, 30, 21, 12,  2],
       [51, 23, 48, 44, 26],
       [33, 17, 32, 49, 10]])

In [43]:
b.shape

(5, 5)

In [44]:
b.size

25

In [45]:
b.ndim

2

In [46]:
b.dtype

dtype('int32')

In [48]:
b.astype('int8')

array([[21, 10, 14, 17, 19],
       [ 6, 12, 39, 47, 12],
       [17, 30, 21, 12,  2],
       [51, 23, 48, 44, 26],
       [33, 17, 32, 49, 10]], dtype=int8)

In [5]:


# shape,size,ndim,dtype


# Array Indexing and Slicing
## Indexing
You can access elements of a NumPy array using indices.

In [49]:
array = np.array([1, 2, 3, 4, 5])

print(array[0])  
print(array[4]) 


1
5


In [50]:
b

array([[21, 10, 14, 17, 19],
       [ 6, 12, 39, 47, 12],
       [17, 30, 21, 12,  2],
       [51, 23, 48, 44, 26],
       [33, 17, 32, 49, 10]])

In [51]:
b[2][2]

21

In [53]:
b[4][3]

49

In [56]:
b[1][4] = 550

In [57]:
b

array([[ 21,  10,  14,  17,  19],
       [  6,  12,  39,  47, 550],
       [ 17,  30,  21,  12,   2],
       [ 51,  23,  48,  44,  26],
       [ 33,  17,  32,  49,  10]])

# Slicing
You can slice arrays to access a subarray.

In [62]:
array = np.array([1, 2, 3, 4, 5])

print(array[1:3]) 
print(array[:3])  
print(array[2:])  
print(array[:])   


[2 3]
[1 2 3]
[3 4 5]
[1 2 3 4 5]


In [65]:
a = np.array(['mayank','krishna','vansh','sachin','manthan'])
a

array(['mayank', 'krishna', 'vansh', 'sachin', 'manthan'], dtype='<U7')

In [66]:
a[1:3]

array(['krishna', 'vansh'], dtype='<U7')

# Array Operations
## Element-wise Operations
NumPy supports element-wise operations on arrays.

In [71]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

print(array1 + array2)  # Output: [5 7 9]
print(array1 * array2)  # Output: [ 4 10 18]
print(array1 - array2) 
print(array2 / array1)  


[5 7 9]
[ 4 10 18]
[-3 -3 -3]
[4.  2.5 2. ]


In [72]:
array1 = np.array([1, 2, 3])
array1*10

array([10, 20, 30])

# Aggregate Functions
NumPy provides many functions to compute aggregates on arrays.

In [73]:
b

array([[ 21,  10,  14,  17,  19],
       [  6,  12,  39,  47, 550],
       [ 17,  30,  21,  12,   2],
       [ 51,  23,  48,  44,  26],
       [ 33,  17,  32,  49,  10]])

In [74]:
max(b)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [75]:
b.max()

550

In [76]:
b.min()

2

In [77]:
b.sum()

1150

In [78]:
b.mean()

46.0

In [79]:
b.std()

103.850662010408

# Reshaping Arrays
You can change the shape of an array without changing its data using the reshape method.

In [80]:
b

array([[ 21,  10,  14,  17,  19],
       [  6,  12,  39,  47, 550],
       [ 17,  30,  21,  12,   2],
       [ 51,  23,  48,  44,  26],
       [ 33,  17,  32,  49,  10]])

In [83]:
print(b.reshape(25,1))

[[ 21]
 [ 10]
 [ 14]
 [ 17]
 [ 19]
 [  6]
 [ 12]
 [ 39]
 [ 47]
 [550]
 [ 17]
 [ 30]
 [ 21]
 [ 12]
 [  2]
 [ 51]
 [ 23]
 [ 48]
 [ 44]
 [ 26]
 [ 33]
 [ 17]
 [ 32]
 [ 49]
 [ 10]]


# Conclusion
NumPy arrays are a powerful tool for numerical computing in Python. They provide efficient storage and operations on large datasets, making them essential for data analysis, scientific computing, and machine learning.